version: '3.8'
services:
  sessao-sicredi:
    image: fernando2812/sessao:latest
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_APPLICATION_NAME: api
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_DRIVER_CLASSNAME: org.h2.Driver
 
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.H2Dialect  # Configuração do Hibernate
     
    ports:
      - '8000:8000'
    networks:
      - java-na-veia
    restart: always

networks:
  java-na-veia:
    driver: bridge
    name: java-na-veia

volumes:
  veiculo-db-data:
    driver: local
