name: Continuous Integration
on: [push]  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Defina a versão do Java desejada (Ex: 8, 11, 17, 21)
          distribution: 'temurin'  # Escolha uma distribuição: 'temurin', 'zulu', 'adopt', etc.
      - name: Build Desafil Back-End Sicredi
        run: mvn spring-boot:build-image
